/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from 'msw';
import { faker } from '@faker-js/faker';
import { baseURL, MAX_ARRAY_LENGTH, next } from '../mock';

export const delete__admin_hooks_hookId = [
  rest.delete(`${baseURL}/admin/hooks/:hookId`, (req, res, ctx) => {
    const resultArray = [[ctx.status(204), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
];
