/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from 'msw';
import { faker } from '@faker-js/faker';
import { baseURL, MAX_ARRAY_LENGTH, next } from '../mock';

export const get__ = [
  rest.get(`${baseURL}/`, (req, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json({
          current_user_url: faker.internet.url(),
          current_user_authorizations_html_url: faker.internet.url(),
          authorizations_url: faker.internet.url(),
          code_search_url: faker.internet.url(),
          commit_search_url: faker.internet.url(),
          emails_url: faker.internet.url(),
          emojis_url: faker.internet.url(),
          events_url: faker.internet.url(),
          feeds_url: faker.internet.url(),
          followers_url: faker.internet.url(),
          following_url: faker.internet.url(),
          gists_url: faker.internet.url(),
          hub_url: faker.internet.url(),
          issue_search_url: faker.internet.url(),
          issues_url: faker.internet.url(),
          keys_url: faker.internet.url(),
          label_search_url: faker.internet.url(),
          notifications_url: faker.internet.url(),
          organization_url: faker.internet.url(),
          organization_repositories_url: faker.internet.url(),
          organization_teams_url: faker.internet.url(),
          public_gists_url: faker.internet.url(),
          rate_limit_url: faker.internet.url(),
          repository_url: faker.internet.url(),
          repository_search_url: faker.internet.url(),
          current_user_repositories_url: faker.internet.url(),
          starred_url: faker.internet.url(),
          starred_gists_url: faker.internet.url(),
          topic_search_url: faker.internet.url(),
          user_url: faker.internet.url(),
          user_organizations_url: faker.internet.url(),
          user_repositories_url: faker.internet.url(),
          user_search_url: faker.internet.url(),
        }),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
];
