/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from 'msw';
import { faker } from '@faker-js/faker';
import { baseURL, MAX_ARRAY_LENGTH, next } from '../mock';

export const patch__admin_hooks_hookId = [
  rest.patch(`${baseURL}/admin/hooks/:hookId`, (req, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json({
          type: faker.lorem.slug(1),
          id: faker.datatype.number(),
          name: faker.name.findName(),
          active: faker.datatype.boolean(),
          events: [
            ...new Array(
              faker.datatype.number({ max: MAX_ARRAY_LENGTH })
            ).keys(),
          ].map(_ => faker.lorem.slug(1)),
          config: {
            url: faker.internet.url(),
            content_type: faker.lorem.slug(1),
            insecure_ssl: faker.lorem.slug(1),
          },
          updated_at: faker.date.past(),
          created_at: faker.date.past(),
          url: faker.internet.url(),
          ping_url: faker.internet.url(),
        }),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
];
